### ISSUE TITLE
Make asylum framework-agnostic?

### ISSUE THREAD

**Issue by sloria** [mattupstate/asylum#1]
Some neat work going on in this repo. I'm curious: have you thought about implementing this in a web framework-agnostic fashion? There seems to be little Flask-specific code here, and the Python ecosystem could really benefit from a generic implementation of the proposed authn/authz system. Flask-Asylum could then exist as a separate package, providing a thin bridge for registering auth providers on an `app`.

**Comment by mattupstate** [comment]
@sloria I've certainly thought about it. Not sure what it looks like yet, but perhaps a `contrib` package for various frameworks.

**Comment by sloria** [comment]
Excellent. Let me know if I can help in any way.

**Comment by mattupstate** [comment]
@sloria here's a blast from the past. No longer framework dependent.

**Comment by sloria** [comment]
Nice work!
